### ISSUE TITLE
Update talkjs_flutter_inappwebview dependency

### ISSUE THREAD

**Issue by Justian-CZ** [talkjs/talkjs-flutter#64]
Hi,

Would it be possible to update the dependency talkjs_flutter_inappwebview?

This fork is currently 202 commits behind and is causing issues for us when building with iOS 18.

**Comment by bugnano** [comment]
Hi,
We're working on it, but it may take some days

**Comment by Justian-CZ** [comment]
Hi, 

Thank you for the quick response!

We saw that the issues surrounding inappwebview and iOS18 are not yet resolved either:
https://github.com/pichillilorenzo/flutter_inappwebview/issues/2278

**Comment by rafalPiotrkowski** [comment]
Hi, im facing the same problem when trying to run my app using Xcode 16. **Ambiguous use of 'evaluateJavaScript(_:completionHandler:)'** Is it possible to fix that issue ?

**Comment by dawid-niedzwiecki** [comment]
Same problem here, cannot update my app due to this issue. :(

**Comment by vickz84259** [comment]
Hey there, my name is Victor. I’m a developer here at TalkJS. I just wanted to update you on the progress. We are looking to have this resolved hopefully by end of business today. Thank you for your patience.

**Comment by vickz84259** [comment]
We shall be making another update to our fork later to bring it up to date with the main flutter inappwebview repository.

Thank you all for your patience and sorry for the inconveniences this issue caused.

**Comment by rafalPiotrkowski** [comment]
Is there any update on this problem. Ive had it on Xcode 16 and iOS 18. Ive downgraded macOS to Sonoma and iOS to 17.7. Now in using Xcode 15.4 and im still getting errors about alkjs_flutter_inappwebview-6.0.9

**Comment by vickz84259** [comment]
@rafalPiotrkowski The issue is resolved. I had left it open because the Firebase libraries hadn't released an update to fix the build issues on their end. But now I see that they released an update on the 26th that fixes the Xcode 16 / iOS 18 issues.

Could you create a new issue with the errors you are receiving if they are not the same as the ones listed in this thread? I'll be more than glad to help you resolve the issue at hand.
